-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 16:05:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Libreria_Libre_actividad_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Libreria_Libre_actividad_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Libreria_Libre_actividad_2` DEFAULT CHARACTER SET utf8 ;
USE `Libreria_Libre_actividad_2` ;

-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Autor` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Autor` (
  `Codigo_autor` INT NOT NULL,
  `Nacionalidad` VARCHAR(50) NOT NULL,
  `Fecha de nacimiento` DATE NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Autor-libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Autor-libro` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Autor-libro` (
  `ISBN_libro` INT NOT NULL,
  `Autor_Codigo_autor` INT NOT NULL,
  INDEX `ISBN_libro_idx` (`ISBN_libro` ASC) VISIBLE,
  INDEX `fk_Autor-libro_Autor1_idx` (`Autor_Codigo_autor` ASC) VISIBLE,
  CONSTRAINT `ISBN_libro`
    FOREIGN KEY (`ISBN_libro`)
    REFERENCES `Libreria_Libre_actividad_2`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor-libro_Autor1`
    FOREIGN KEY (`Autor_Codigo_autor`)
    REFERENCES `Libreria_Libre_actividad_2`.`Autor` (`Codigo_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Cliente` (
  `Cedula` INT NOT NULL,
  `Nombre` VARCHAR(80) NOT NULL,
  `E-mail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Compra libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Compra libro` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Compra libro` (
  `Cliente_Cedula` INT NOT NULL,
  `Libro_ISBN` INT NOT NULL,
  INDEX `fk_Compra libro_Cliente1_idx` (`Cliente_Cedula` ASC) VISIBLE,
  INDEX `fk_Compra libro_Libro1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Compra libro_Cliente1`
    FOREIGN KEY (`Cliente_Cedula`)
    REFERENCES `Libreria_Libre_actividad_2`.`Cliente` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra libro_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `Libreria_Libre_actividad_2`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Editorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Editorial` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Editorial` (
  `Nombre_editorial` VARCHAR(30) NOT NULL,
  `CantidadDeLibrosDisponibles` INT NOT NULL,
  PRIMARY KEY (`Nombre_editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Libro` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Libro` (
  `ISBN` INT NOT NULL,
  `Titulo` VARCHAR(80) NULL,
  `Numero_paginas` VARCHAR(5) NULL,
  `Nombre_editorial` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Libro_Editorial_idx` (`Nombre_editorial` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Editorial`
    FOREIGN KEY (`Nombre_editorial`)
    REFERENCES `Libreria_Libre_actividad_2`.`Editorial` (`Nombre_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria_Libre_actividad_2`.`Telefono cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Libreria_Libre_actividad_2`.`Telefono cliente` ;

CREATE TABLE IF NOT EXISTS `Libreria_Libre_actividad_2`.`Telefono cliente` (
  `Cedula` INT NOT NULL,
  `Telefono` INT NOT NULL,
  INDEX `Cedula_idx` (`Cedula` ASC) VISIBLE,
  CONSTRAINT `Cedula`
    FOREIGN KEY (`Cedula`)
    REFERENCES `Libreria_Libre_actividad_2`.`Cliente` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
