-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 16:59:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Busca_Libre_actividad_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Busca_Libre_actividad_1` ;

-- -----------------------------------------------------
-- Schema Busca_Libre_actividad_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Busca_Libre_actividad_1` DEFAULT CHARACTER SET utf8 ;
USE `Busca_Libre_actividad_1` ;

-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Autor` (
  `ID` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaDeNacimiento` DATE NULL,
  `LibrosEnExistencia` INT NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Cliente` (
  `Cedula` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `CantidadDeLibrosComprados` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Compra` (
  `Consecutivo` INT NOT NULL,
  `Cliente_Cedula` INT NOT NULL,
  `Libro_ISBN` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Consecutivo`),
  INDEX `fk_Compra_Cliente1_idx` (`Cliente_Cedula` ASC) VISIBLE,
  INDEX `fk_Compra_Libro1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Cliente1`
    FOREIGN KEY (`Cliente_Cedula`)
    REFERENCES `Busca_Libre_actividad_1`.`Cliente` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `Busca_Libre_actividad_1`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Editorial` (
  `Nombre` VARCHAR(50) NOT NULL,
  `CantidadDeLibros` INT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Libro` (
  `ISBN` VARCHAR(30) NOT NULL,
  `Titulo` VARCHAR(40) NULL,
  `ID_Autor` VARCHAR(40) NULL,
  `numneroDePaginas` INT NULL,
  `Editorial_Nombre1` VARCHAR(50) NOT NULL,
  `CantidadDeCopias` INT NULL,
  INDEX `fk_Libro_Editorial1_idx` (`Editorial_Nombre1` ASC) VISIBLE,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `fk_Libro_Editorial1`
    FOREIGN KEY (`Editorial_Nombre1`)
    REFERENCES `Busca_Libre_actividad_1`.`Editorial` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`Libro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`Libro_autor` (
  `Autor_ID` INT NOT NULL,
  `Libro_ISBN` VARCHAR(30) NOT NULL,
  INDEX `fk_Libro_autor_Autor1_idx` (`Autor_ID` ASC) VISIBLE,
  INDEX `fk_Libro_autor_Libro1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_autor_Autor1`
    FOREIGN KEY (`Autor_ID`)
    REFERENCES `Busca_Libre_actividad_1`.`Autor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_autor_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `Busca_Libre_actividad_1`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Busca_Libre_actividad_1`.`NumeroDeTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Busca_Libre_actividad_1`.`NumeroDeTelefono` (
  `Telefono` INT NULL,
  `Cliente_Cedula` INT NOT NULL,
  INDEX `fk_NumeroDeTelefono_Cliente1_idx` (`Cliente_Cedula` ASC) VISIBLE,
  PRIMARY KEY (`Cliente_Cedula`),
  CONSTRAINT `fk_NumeroDeTelefono_Cliente1`
    FOREIGN KEY (`Cliente_Cedula`)
    REFERENCES `Busca_Libre_actividad_1`.`Cliente` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
