-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 23:19:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`categoria` (
  `ID_categoria` INT NOT NULL,
  `Nombre_categoria` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Edad_sugerida` INT NOT NULL,
  PRIMARY KEY (`ID_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`editorial` (
  `Nombre_editorial` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre_editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`libro` (
  `ISBN` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nombre_editorial` VARCHAR(45) NOT NULL,
  `ID_categoria libro` INT NOT NULL,
  `ID_autor` INT NOT NULL,
  `Numero_paginas` INT NOT NULL,
  `Valor` INT NOT NULL,
  `Fecha_publicacion` DATE NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_idcategoria_idx` (`ID_categoria libro` ASC) VISIBLE,
  INDEX `fk_Nombreeditorial_idx` (`Nombre_editorial` ASC) VISIBLE,
  CONSTRAINT `fk_idcategorialibro`
    FOREIGN KEY (`ID_categoria libro`)
    REFERENCES `libreria`.`categoria` (`ID_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Nombreeditorial`
    FOREIGN KEY (`Nombre_editorial`)
    REFERENCES `libreria`.`editorial` (`Nombre_editorial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`autor` (
  `ID_autor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`autoria` (
  `ISBN` INT NOT NULL,
  `ID_autor` INT NOT NULL,
  INDEX `fk_ISBN_idx` (`ISBN` ASC) VISIBLE,
  INDEX `fk_IDautor_idx` (`ID_autor` ASC) VISIBLE,
  CONSTRAINT `fk_ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `libreria`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ID_autor`
    FOREIGN KEY (`ID_autor`)
    REFERENCES `libreria`.`autor` (`ID_autor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`clientes` (
  `ID_cliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`compra` (
  `ID_compra` INT NOT NULL,
  `ID_cliente` INT NOT NULL,
  `ISBN` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`ID_compra`),
  INDEX `fk_IDcliente_idx` (`ID_cliente` ASC) VISIBLE,
  INDEX `fk_Infolibro_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Infolibro`
    FOREIGN KEY (`ISBN`)
    REFERENCES `libreria`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IDclientecompra`
    FOREIGN KEY (`ID_cliente`)
    REFERENCES `libreria`.`clientes` (`ID_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
