-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 05:56:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`categoria` (
  `ID categoria` INT NOT NULL,
  `Nombre categoria` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Edad sugerida` INT NOT NULL,
  PRIMARY KEY (`ID categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`editorial` (
  `Nombre editorial` VARCHAR(45) NOT NULL,
  `ISBN editorial` INT NOT NULL,
  `ID autor` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Nombre editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`libro` (
  `ISBN` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nombre editorial` VARCHAR(45) NOT NULL,
  `ID categoria libro` INT NOT NULL,
  `ID autor` INT NOT NULL,
  `Numero paginas` INT NOT NULL,
  `Valor` INT NOT NULL,
  `Fecha publicacion` DATE NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_idcategoria_idx` (`ID categoria libro` ASC) VISIBLE,
  INDEX `fk_Nombreeditorial_idx` (`Nombre editorial` ASC) VISIBLE,
  CONSTRAINT `fk_idcategorialibro`
    FOREIGN KEY (`ID categoria libro`)
    REFERENCES `libreria`.`categoria` (`ID categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Nombreeditorial`
    FOREIGN KEY (`Nombre editorial`)
    REFERENCES `libreria`.`editorial` (`Nombre editorial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`autor` (
  `ID autor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha nacimiento` DATE NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  `ISBN` INT NOT NULL,
  PRIMARY KEY (`ID autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`autoria` (
  `ISBN autorias` INT NOT NULL,
  `ID autores` INT NOT NULL,
  `Cantidad Autores` INT NOT NULL,
  INDEX `fk_ISBN_idx` (`ISBN autorias` ASC) VISIBLE,
  INDEX `fk_IDautor_idx` (`ID autores` ASC) VISIBLE,
  CONSTRAINT `fk_ISBNautoria`
    FOREIGN KEY (`ISBN autorias`)
    REFERENCES `libreria`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IDautor`
    FOREIGN KEY (`ID autores`)
    REFERENCES `libreria`.`autor` (`ID autor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`clientes` (
  `ID cliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`ID cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria`.`compra` (
  `ID compra` INT NOT NULL,
  `ID cliente compra` INT NOT NULL,
  `ISBN cliente` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`ID compra`),
  INDEX `fk_IDcliente_idx` (`ID cliente compra` ASC) VISIBLE,
  INDEX `fk_Infolibro_idx` (`ISBN cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Infolibro`
    FOREIGN KEY (`ISBN cliente`)
    REFERENCES `libreria`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IDclientecompra`
    FOREIGN KEY (`ID cliente compra`)
    REFERENCES `libreria`.`clientes` (`ID cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
