-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 22:57:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreríaDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreríaDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreríaDb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema luis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema luis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luis` DEFAULT CHARACTER SET utf8mb3 ;
USE `libreríaDb` ;

-- -----------------------------------------------------
-- Table `libreríaDb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Clientes` (
  `Cédula` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Primer_Apellido` VARCHAR(45) NULL,
  `Segundo_Apellido` VARCHAR(45) NULL,
  `Fecha_Nacimiento` DATE NULL,
  PRIMARY KEY (`Cédula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Compras` (
  `Id` INT NOT NULL,
  `Fecha` DATE NULL,
  `Precio` DECIMAL(6,2) NULL,
  `Total` DECIMAL(10,4) NULL,
  `Cliente_Cédula` INT NOT NULL,
  PRIMARY KEY (`Id`, `Cliente_Cédula`),
  INDEX `fk_Compras_Clientes1_idx` (`Cliente_Cédula` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Clientes1`
    FOREIGN KEY (`Cliente_Cédula`)
    REFERENCES `libreríaDb`.`Clientes` (`Cédula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Nacionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Nacionalidades` (
  `Id` INT NOT NULL,
  `País` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Autores` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Primer_Apellido` VARCHAR(45) NULL,
  `Segundo_Apellido` VARCHAR(45) NULL,
  `Fecha_Nacimiento` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Nacionalidades x Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Nacionalidades x Autor` (
  `Nacionalidad_Id` INT NOT NULL,
  `Autor_Id` INT NOT NULL,
  PRIMARY KEY (`Nacionalidad_Id`, `Autor_Id`),
  INDEX `fk_Nacionalidades x Autor_Autores1_idx` (`Autor_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Nacionalidades x Autor_Nacionalidades1`
    FOREIGN KEY (`Nacionalidad_Id`)
    REFERENCES `libreríaDb`.`Nacionalidades` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nacionalidades x Autor_Autores1`
    FOREIGN KEY (`Autor_Id`)
    REFERENCES `libreríaDb`.`Autores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Editoriales` (
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Libros` (
  `ISBN` INT NOT NULL,
  `Título` VARCHAR(60) NULL,
  `Número_Páginas` INT NULL,
  `Editorial_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Libros_Editoriales1_idx` (`Editorial_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Libros_Editoriales1`
    FOREIGN KEY (`Editorial_Nombre`)
    REFERENCES `libreríaDb`.`Editoriales` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Libros x Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Libros x Autor` (
  `Autor_Id` INT NOT NULL,
  `Libros_ISBN` INT NOT NULL,
  PRIMARY KEY (`Autor_Id`, `Libros_ISBN`),
  INDEX `fk_Libros x Autor_Libros1_idx` (`Libros_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Libros x Autor_Autores1`
    FOREIGN KEY (`Autor_Id`)
    REFERENCES `libreríaDb`.`Autores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros x Autor_Libros1`
    FOREIGN KEY (`Libros_ISBN`)
    REFERENCES `libreríaDb`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Inventarios` (
  `Id` INT NOT NULL,
  `Cantidad` INT NULL,
  `Libro_ISBN` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Inventarios_Libros1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Inventarios_Libros1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `libreríaDb`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Géneros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Géneros` (
  `Id` INT NOT NULL,
  `Género` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Géneros x Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Géneros x Libro` (
  `Géneros_Id` INT NOT NULL,
  `Libro_ISBN` INT NOT NULL,
  PRIMARY KEY (`Géneros_Id`, `Libro_ISBN`),
  INDEX `fk_Géneros x Libro_Libros1_idx` (`Libro_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Géneros x Libro_Géneros1`
    FOREIGN KEY (`Géneros_Id`)
    REFERENCES `libreríaDb`.`Géneros` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Géneros x Libro_Libros1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `libreríaDb`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreríaDb`.`Libros en compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreríaDb`.`Libros en compra` (
  `Cantidad` INT NULL,
  `Subtotal` DECIMAL(6,2) NULL,
  `Libro_ISBN` INT NOT NULL,
  `Compra_Id` INT NOT NULL,
  PRIMARY KEY (`Libro_ISBN`, `Compra_Id`),
  INDEX `fk_Libros en compra_Compras1_idx` (`Compra_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Libros en compra_Libros1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `libreríaDb`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libros en compra_Compras1`
    FOREIGN KEY (`Compra_Id`)
    REFERENCES `libreríaDb`.`Compras` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `luis` ;

-- -----------------------------------------------------
-- Table `luis`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`autor` (
  `Id_autor` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Apellido1` VARCHAR(50) NULL,
  `Apellido2` VARCHAR(50) NULL,
  `Fecha_nacimiento` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`Id_autor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`cliente` (
  `Id_cliente` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Apellido1` VARCHAR(50) NULL,
  `Apellido2` VARCHAR(50) NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`editorial` (
  `Nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`libro` (
  `ISBN` VARCHAR(15) NOT NULL,
  `Titulo` VARCHAR(50) NULL DEFAULT NULL,
  `Num_paginas` INT NULL DEFAULT NULL,
  `Nombre_editorial` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `Nombre_editorial` (`Nombre_editorial` ASC) VISIBLE,
  CONSTRAINT `libro_ibfk_1`
    FOREIGN KEY (`Nombre_editorial`)
    REFERENCES `luis`.`editorial` (`Nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`compra` (
  `ISBN` VARCHAR(15) NOT NULL,
  `Id_cliente` VARCHAR(15) NOT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT NULL,
  INDEX `ISBN` (`ISBN` ASC) VISIBLE,
  INDEX `Id_cliente` (`Id_cliente` ASC) VISIBLE,
  PRIMARY KEY (`ISBN`, `Id_cliente`),
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `luis`.`libro` (`ISBN`),
  CONSTRAINT `compra_ibfk_2`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `luis`.`cliente` (`Id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`escribir_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`escribir_libro` (
  `ISBN` VARCHAR(15) NOT NULL,
  `Id_autor` INT NOT NULL,
  INDEX `ISBN` (`ISBN` ASC) VISIBLE,
  INDEX `Id_autor` (`Id_autor` ASC) VISIBLE,
  PRIMARY KEY (`ISBN`, `Id_autor`),
  CONSTRAINT `escribir_libro_ibfk_1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `luis`.`libro` (`ISBN`),
  CONSTRAINT `escribir_libro_ibfk_2`
    FOREIGN KEY (`Id_autor`)
    REFERENCES `luis`.`autor` (`Id_autor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`Nacionalidad` (
  `Id_nacionalidad` VARCHAR(50) NOT NULL,
  `País` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id_nacionalidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `luis`.`Nacionalidad autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luis`.`Nacionalidad autor` (
  `autor_Id_autor` INT NOT NULL,
  `Nacionalidad_Id_nacionalidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`autor_Id_autor`, `Nacionalidad_Id_nacionalidad`),
  INDEX `fk_Nacionalidad autor_autor1_idx` (`autor_Id_autor` ASC) VISIBLE,
  INDEX `fk_Nacionalidad autor_Nacionalidad1_idx` (`Nacionalidad_Id_nacionalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Nacionalidad autor_autor1`
    FOREIGN KEY (`autor_Id_autor`)
    REFERENCES `luis`.`autor` (`Id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nacionalidad autor_Nacionalidad1`
    FOREIGN KEY (`Nacionalidad_Id_nacionalidad`)
    REFERENCES `luis`.`Nacionalidad` (`Id_nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
