-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 15:28:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria-jorge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria-jorge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria-jorge` DEFAULT CHARACTER SET utf8 ;
USE `libreria-jorge` ;

-- -----------------------------------------------------
-- Table `libreria-jorge`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`categoria` (
  `ID categoria` INT NOT NULL,
  `Nombre categoria` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Edad sugerida` INT NOT NULL,
  PRIMARY KEY (`ID categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`editorial` (
  `Nombre editorial` VARCHAR(45) NOT NULL,
  `ISBN editorial` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`Nombre editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`libro` (
  `ISBN` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nombre editorial` VARCHAR(45) NOT NULL,
  `ID categoria libro` INT NOT NULL,
  `Numero paginas` INT NOT NULL,
  `Valor` INT NOT NULL,
  `Fecha publicacion` DATE NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_idcategoria_idx` (`ID categoria libro` ASC) VISIBLE,
  INDEX `fk_Nombreeditorial_idx` (`Nombre editorial` ASC) VISIBLE,
  CONSTRAINT `fk_idcategorialibro`
    FOREIGN KEY (`ID categoria libro`)
    REFERENCES `libreria-jorge`.`categoria` (`ID categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Nombreeditorial`
    FOREIGN KEY (`Nombre editorial`)
    REFERENCES `libreria-jorge`.`editorial` (`Nombre editorial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`autor` (
  `ID autor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha nacimiento` DATE NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  `ISBN` INT NOT NULL,
  PRIMARY KEY (`ID autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`autoria` (
  `ISBN autorias` INT NOT NULL,
  `ID autores` INT NOT NULL,
  INDEX `fk_ISBN_idx` (`ISBN autorias` ASC) VISIBLE,
  INDEX `fk_IDautor_idx` (`ID autores` ASC) VISIBLE,
  CONSTRAINT `fk_ISBNautoria`
    FOREIGN KEY (`ISBN autorias`)
    REFERENCES `libreria-jorge`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IDautor`
    FOREIGN KEY (`ID autores`)
    REFERENCES `libreria-jorge`.`autor` (`ID autor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`clientes` (
  `ID cliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`ID cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`compra` (
  `ID compra` INT NOT NULL,
  `ID cliente compra` INT NOT NULL,
  `ISBN cliente` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`ID compra`),
  INDEX `fk_IDcliente_idx` (`ID cliente compra` ASC) VISIBLE,
  INDEX `fk_Infolibro_idx` (`ISBN cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Infolibro`
    FOREIGN KEY (`ISBN cliente`)
    REFERENCES `libreria-jorge`.`libro` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IDclientecompra`
    FOREIGN KEY (`ID cliente compra`)
    REFERENCES `libreria-jorge`.`clientes` (`ID cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`telefono-cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`telefono-cliente` (
  `id-cliente` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  INDEX `fk-cliente_idx` (`id-cliente` ASC) VISIBLE,
  CONSTRAINT `fk-cliente`
    FOREIGN KEY (`id-cliente`)
    REFERENCES `libreria-jorge`.`clientes` (`ID cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria-jorge`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria-jorge`.`Nacionalidad` (
  `ID autor` INT NOT NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  INDEX `fk_autor_idx` (`ID autor` ASC) VISIBLE,
  CONSTRAINT `fk_autor`
    FOREIGN KEY (`ID autor`)
    REFERENCES `libreria-jorge`.`autor` (`ID autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
