-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 00:16:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Libreria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Libreria` DEFAULT CHARACTER SET utf8 ;
USE `Libreria` ;

-- -----------------------------------------------------
-- Table `Libreria`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Autores` (
  `Id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`Id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Editoriales` (
  `nombre_editorial` VARCHAR(75) NOT NULL,
  `ISBN` VARCHAR(10) NULL,
  PRIMARY KEY (`nombre_editorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Categoria` (
  `ID_categoria` VARCHAR(10) NOT NULL,
  `Nombre_categoria` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Libros` (
  `ISBN` VARCHAR(10) NOT NULL,
  `titulo` VARCHAR(75) NULL,
  `numero_paginas` INT NULL,
  `nombre_editorial` VARCHAR(75) NULL,
  `valor_compra` INT NULL,
  `valor_venta` INT NULL,
  `fecha_publicacion` DATE NULL,
  `ID_categoria` VARCHAR(10) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `nombre_editorial_idx` (`nombre_editorial` ASC) VISIBLE,
  INDEX `ID_categoria_idx` (`ID_categoria` ASC) VISIBLE,
  CONSTRAINT `nombre_editorial`
    FOREIGN KEY (`nombre_editorial`)
    REFERENCES `Libreria`.`Editoriales` (`nombre_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_categoria`
    FOREIGN KEY (`ID_categoria`)
    REFERENCES `Libreria`.`Categoria` (`ID_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Escritura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Escritura` (
  `ID_autor` INT NOT NULL,
  `ISBN` VARCHAR(10) NOT NULL,
  INDEX `codigo_idx` (`ID_autor` ASC) VISIBLE,
  INDEX `ISBN_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `codigo`
    FOREIGN KEY (`ID_autor`)
    REFERENCES `Libreria`.`Autores` (`Id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `Libreria`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Clientes` (
  `ID_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Ventas` (
  `ID_venta` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(10) NULL,
  `id_cliente` INT NULL,
  `cantidad_libro` INT NULL,
  `Valor_total` INT NULL,
  `Fecha_venta` DATE NULL,
  PRIMARY KEY (`ID_venta`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `ID_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Libreria`.`Clientes` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `Libreria`.`Libros` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libreria`.`Telefono_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libreria`.`Telefono_clientes` (
  `ID_clientes` INT NULL,
  `telefono` VARCHAR(45) NULL,
  CONSTRAINT `id_clientes`
    FOREIGN KEY (`ID_clientes`)
    REFERENCES `Libreria`.`Clientes` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
